<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows10.0.19041.0</TargetFramework>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <ApplicationIcon>Assets\app-icon.ico</ApplicationIcon>
    <AssemblyName>Archura.Windrop</AssemblyName>
    <RootNamespace>Windrop.App</RootNamespace>
    <Version>1.0.0</Version>
    <AssemblyVersion>1.0.0.0</AssemblyVersion>
    <FileVersion>1.0.0.0</FileVersion>
    <Product>Archura Windrop</Product>
    <Company>Archura</Company>
    <Copyright>Copyright © 2026 Archura</Copyright>
    <ImplicitUsings>disable</ImplicitUsings>
  </PropertyGroup>
  <ItemGroup>
    <Resource Include="Assets\app-icon.ico" />
    <Resource Include="Assets\app-icon.png" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Windrop.Domain\Windrop.Domain.csproj" />
    <ProjectReference Include="..\Windrop.Data\Windrop.Data.csproj" />
    <ProjectReference Include="..\Windrop.Infrastructure\Windrop.Infrastructure.csproj" />
  </ItemGroup>
</Project>
